//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiLH.Context
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Validation;
    using System.ComponentModel.DataAnnotations;


    public partial class LienHe
    {
        
        [Key]   
        public int id { get; set; }
   
        [Display(Name ="Nhập tên")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string Ten { get; set; }

        [Display(Name ="Phone")]
        [Required(ErrorMessage ="Phải nhập {0}")]
        [Phone(ErrorMessage ="Nhập đúng kiểu số điện thoại")]
        [StringLength(20, MinimumLength = 9,ErrorMessage ="Số điện thoại hơn 9 số")]
        public string Phone { get; set; }

    }
}
